prop.pdf: qsim_proposalanddiscr.md q.bib
	pandoc qsim_proposalanddiscr.md --filter pandoc-citeproc -o prop.pdf

detail.pdf: qsim_pathintegral.md q.bib
	pandoc qsim_pathintegral.md --filter pandoc-citeproc -o detail.pdf --pdf-engine=xelatex